name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '12.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 6.10.0
    - name: Generate pnpm file
      run: pnpm install
    - uses: jacobwgillespie/setup-node@cache-pnpm
      with:
        node-version: ${{ matrix.version }}
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
    - name: upload screenshot
      if: ${{ always() }}
      uses: actions/upload-artifact@master
      with:
        name: pnpm-lock.yml
        path: pnpm-lock.yml
